"use client"

import React from "react"
import { useSettings } from "@/atoms/settings"
import { useMount } from "react-use"
import { smartSelect_normalizeEpisodes } from "@/app/(main)/torrents/smart-select/_lib/utils"

export default function Page() {

    const { settings } = useSettings()

    useMount(() => {

        // console.log(rakun.parse("[Judas] Blue Lock - S01E01v2.mkv"))
        console.log(smartSelect_normalizeEpisodes([
            {
                "info": {
                    "availability": 0,
                    "index": 0,
                    "is_seed": false,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E22v2.mkv",
                    "piece_range": [
                        0,
                        613,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 643680711,
                },
                "originalName": "[Judas] Blue Lock - S01E22v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E22v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "22",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 1,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E02v2.mkv",
                    "piece_range": [
                        613,
                        981,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 385186666,
                },
                "originalName": "[Judas] Blue Lock - S01E02v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E02v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "2",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 2,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E03v2.mkv",
                    "piece_range": [
                        981,
                        1349,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 385683922,
                },
                "originalName": "[Judas] Blue Lock - S01E03v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E03v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "3",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 3,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E04v2.mkv",
                    "piece_range": [
                        1349,
                        1727,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 396874696,
                },
                "originalName": "[Judas] Blue Lock - S01E04v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E04v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "4",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 4,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E05v2.mkv",
                    "piece_range": [
                        1727,
                        2116,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 407801865,
                },
                "originalName": "[Judas] Blue Lock - S01E05v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E05v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "5",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 5,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E06v2.mkv",
                    "piece_range": [
                        2116,
                        2515,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 418479308,
                },
                "originalName": "[Judas] Blue Lock - S01E06v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E06v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "6",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 6,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E07v2.mkv",
                    "piece_range": [
                        2515,
                        2891,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 394752609,
                },
                "originalName": "[Judas] Blue Lock - S01E07v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E07v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "7",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 7,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E08v2.mkv",
                    "piece_range": [
                        2891,
                        3231,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 356167833,
                },
                "originalName": "[Judas] Blue Lock - S01E08v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E08v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "8",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 8,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E09v2.mkv",
                    "piece_range": [
                        3231,
                        3670,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 460061444,
                },
                "originalName": "[Judas] Blue Lock - S01E09v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E09v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "9",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 9,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E10v2.mkv",
                    "piece_range": [
                        3670,
                        4225,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 581544839,
                },
                "originalName": "[Judas] Blue Lock - S01E10v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E10v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "10",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 10,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E11v2.mkv",
                    "piece_range": [
                        4225,
                        4612,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 406766575,
                },
                "originalName": "[Judas] Blue Lock - S01E11v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E11v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "11",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 11,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E12v2.mkv",
                    "piece_range": [
                        4612,
                        4900,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 302058286,
                },
                "originalName": "[Judas] Blue Lock - S01E12v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E12v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "12",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 12,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E13v2.mkv",
                    "piece_range": [
                        4900,
                        5440,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 565378808,
                },
                "originalName": "[Judas] Blue Lock - S01E13v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E13v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "13",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 13,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E14v2.mkv",
                    "piece_range": [
                        5440,
                        5859,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 439513296,
                },
                "originalName": "[Judas] Blue Lock - S01E14v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E14v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "14",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 14,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E15v2.mkv",
                    "piece_range": [
                        5859,
                        6344,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 508231032,
                },
                "originalName": "[Judas] Blue Lock - S01E15v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E15v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "15",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 15,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E16v2.mkv",
                    "piece_range": [
                        6344,
                        6711,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 384816323,
                },
                "originalName": "[Judas] Blue Lock - S01E16v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E16v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "16",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 16,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E17v2.mkv",
                    "piece_range": [
                        6711,
                        7226,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 540285962,
                },
                "originalName": "[Judas] Blue Lock - S01E17v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E17v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "17",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 17,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E18v2.mkv",
                    "piece_range": [
                        7226,
                        7763,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 562874300,
                },
                "originalName": "[Judas] Blue Lock - S01E18v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E18v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "18",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 18,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E19v2.mkv",
                    "piece_range": [
                        7763,
                        8189,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 447532810,
                },
                "originalName": "[Judas] Blue Lock - S01E19v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E19v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "19",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 19,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E20v2.mkv",
                    "piece_range": [
                        8189,
                        8751,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 589209720,
                },
                "originalName": "[Judas] Blue Lock - S01E20v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E20v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "20",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 20,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E21v2.mkv",
                    "piece_range": [
                        8751,
                        9301,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 576900566,
                },
                "originalName": "[Judas] Blue Lock - S01E21v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E21v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "21",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 21,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E01v2.mkv",
                    "piece_range": [
                        9301,
                        9717,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 435709128,
                },
                "originalName": "[Judas] Blue Lock - S01E01v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E01v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "1",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 22,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E23v2.mkv",
                    "piece_range": [
                        9717,
                        10097,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 398195944,
                },
                "originalName": "[Judas] Blue Lock - S01E23v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E23v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "23",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
            {
                "info": {
                    "availability": 0,
                    "index": 23,
                    "name": "[Judas] Blue Lock (Season 1) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]/[Judas] Blue Lock - S01E24v2.mkv",
                    "piece_range": [
                        10097,
                        10512,
                    ],
                    "priority": 1,
                    "progress": 0,
                    "size": 435673435,
                },
                "originalName": "[Judas] Blue Lock - S01E24v2.mkv",
                "parsed": {
                    "filename": "[Judas] Blue Lock - S01E24v2.mkv",
                    "extension": "mkv",
                    "subber": "Judas",
                    "season": "1",
                    "episode": "24",
                    "name": "Blue Lock",
                },
                "trueEpisode": 0,
                "season": 1,
            },
        ]))
    })

    return (
        <div>
            {/*{JSON.stringify(torrentQueue, null, 2)}*/}
        </div>
    )

}
