import "../styles/globals.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TitleBar } from "@/components/application/titlebar";
import { ClientProviders } from "@/components/client-providers";
import { MainLayout } from "@/components/application/main-layout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout(
    {
        children,
    }: {
        children: React.ReactNode
    }) {

    return (
        <html lang="en">
        <body className={inter.className}>
        <ClientProviders>
            <TitleBar/>
            <MainLayout>
                {children}
            </MainLayout>
        </ClientProviders>
        </body>
        </html>
    )
}
