name: Create Release Draft

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "CHANGELOG.md"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Get version from package.json
        id: app-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Generate Release Notes
        run: python ./.github/scripts/generate-release-notes.py

      - name: Create Release Draft
        id: create_release_draft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.app-version.outputs.current-version}}
          release_name: v${{ steps.app-version.outputs.current-version}}
          body_path: "changelog-temp.md"
          draft: true
          prerelease: false
